{% macro clean_location(location_column) %}
    {% set clean_col = remove_accents(location_column) %}
    CASE
        -- 5 Thành phố trực thuộc trung ương
        WHEN {{ clean_col }} ~ '(ho chi minh|hcm|sai gon|saigon|tphcm|tp\.hcm|hochiminh)' THEN 'Hồ Chí Minh'
        WHEN {{ clean_col }} ~ '(ha noi|hanoi|tp hn|tphn|tp\.hn)' THEN 'Hà Nội'
        WHEN {{ clean_col }} ~ '(da nang|danang|tp dn|tpdn|tp\.dn)' THEN 'Đà Nẵng'
        WHEN {{ clean_col }} ~ '(hai phong|haiphong|tp hp|tphp|tp\.hp)' THEN 'Hải Phòng'
        WHEN {{ clean_col }} ~ '(can tho|cantho|tp ct|tpct|tp\.ct)' THEN 'Cần Thơ'

        -- Các tỉnh miền Bắc
        WHEN {{ clean_col }} ~ '(bac giang| bacgiang)' THEN 'Bắc Giang'
        WHEN {{ clean_col }} ~ '(bac kan|backan)' THEN 'Bắc Kạn'
        WHEN {{ clean_col }} ~ '(bac ninh|bacninh)' THEN 'Bắc Ninh'
        WHEN {{ clean_col }} ~ '(cao bang|caobang)' THEN 'Cao Bằng'
        WHEN {{ clean_col }} ~ '(dien bien|dienbien)' THEN 'Điện Biên'
        WHEN {{ clean_col }} ~ '(ha giang|hagiang)' THEN 'Hà Giang'
        WHEN {{ clean_col }} ~ '(ha nam|hanam)' THEN 'Hà Nam'
        WHEN {{ clean_col }} ~ '(hai duong|haiduong)' THEN 'Hải Dương'
        WHEN {{ clean_col }} ~ '(hoa binh|hoabinh)' THEN 'Hòa Bình'
        WHEN {{ clean_col }} ~ '(hung yen|hungyen)' THEN 'Hưng Yên'
        WHEN {{ clean_col }} ~ '(lai chau|laichau)' THEN 'Lai Châu'
        WHEN {{ clean_col }} ~ '(lang son|langson)' THEN 'Lạng Sơn'
        WHEN {{ clean_col }} ~ '(lao cai|laocai)' THEN 'Lào Cai'
        WHEN {{ clean_col }} ~ '(nam dinh|namdinh)' THEN 'Nam Định'
        WHEN {{ clean_col }} ~ '(ninh binh|ninhbinh)' THEN 'Ninh Bình'
        WHEN {{ clean_col }} ~ '(phu tho|phutho)' THEN 'Phú Thọ'
        WHEN {{ clean_col }} ~ '(quang ninh|quangninh)' THEN 'Quảng Ninh'
        WHEN {{ clean_col }} ~ '(son la|sonla)' THEN 'Sơn La'
        WHEN {{ clean_col }} ~ '(thai binh|thaibinh)' THEN 'Thái Bình'
        WHEN {{ clean_col }} ~ '(thai nguyen|thainguyen)' THEN 'Thái Nguyên'
        WHEN {{ clean_col }} ~ '(tuyen quang|tuyenquang)' THEN 'Tuyên Quang'
        WHEN {{ clean_col }} ~ '(vinh phuc|vinhphuc)' THEN 'Vĩnh Phúc'
        WHEN {{ clean_col }} ~ '(yen bai|yenbai)' THEN 'Yên Bái'

        -- Các tỉnh miền Trung & Tây Nguyên
        WHEN {{ clean_col }} ~ '(ha tinh|hatinh)' THEN 'Hà Tĩnh'
        WHEN {{ clean_col }} ~ '(nghe an|nghean)' THEN 'Nghệ An'
        WHEN {{ clean_col }} ~ '(quang binh|quangbinh)' THEN 'Quảng Bình'
        WHEN {{ clean_col }} ~ '(quang tri|quangtri)' THEN 'Quảng Trị'
        WHEN {{ clean_col }} ~ '(thanh hoa|thanhhoa)' THEN 'Thanh Hóa'
        WHEN {{ clean_col }} ~ '(thua thien hue|hue)' THEN 'Thừa Thiên Huế'
        WHEN {{ clean_col }} ~ '(binh dinh|bindinh)' THEN 'Bình Định'
        WHEN {{ clean_col }} ~ '(binh thuan|binhthuan)' THEN 'Bình Thuận'
        WHEN {{ clean_col }} ~ '(khanh hoa|khanhhoa)' THEN 'Khánh Hòa'
        WHEN {{ clean_col }} ~ '(ninh thuan|ninhthuan)' THEN 'Ninh Thuận'
        WHEN {{ clean_col }} ~ '(phu yen|phuyen)' THEN 'Phú Yên'
        WHEN {{ clean_col }} ~ '(quang nam|quangnam)' THEN 'Quảng Nam'
        WHEN {{ clean_col }} ~ '(quang ngai|quangngai)' THEN 'Quảng Ngãi'
        WHEN {{ clean_col }} ~ '(dak lak|daklak)' THEN 'Đắk Lắk'
        WHEN {{ clean_col }} ~ '(dak nong|daknong)' THEN 'Đắk Nông'
        WHEN {{ clean_col }} ~ '(gia lai|gialai)' THEN 'Gia Lai'
        WHEN {{ clean_col }} ~ '(kon tum|kontum)' THEN 'Kon Tum'
        WHEN {{ clean_col }} ~ '(lam dong|lamdong)' THEN 'Lâm Đồng'

        -- Các tỉnh miền Nam
        WHEN {{ clean_col }} ~ '(ba ria|vung tau|brvt|br-vt)' THEN 'Bà Rịa - Vũng Tàu'
        WHEN {{ clean_col }} ~ '(binh duong|binhduong)' THEN 'Bình Dương'
        WHEN {{ clean_col }} ~ '(binh phuoc|binhphuoc)' THEN 'Bình Phước'
        WHEN {{ clean_col }} ~ '(dong nai|dongnai)' THEN 'Đồng Nai'
        WHEN {{ clean_col }} ~ '(tay ninh|tayninh)' THEN 'Tây Ninh'
        WHEN {{ clean_col }} ~ '(an giang|angiang)' THEN 'An Giang'
        WHEN {{ clean_col }} ~ '(bac lieu|baclieu)' THEN 'Bạc Liêu'
        WHEN {{ clean_col }} ~ '(ben tre|bentre)' THEN 'Bến Tre'
        WHEN {{ clean_col }} ~ '(ca mau|camau)' THEN 'Cà Mau'
        WHEN {{ clean_col }} ~ '(dong thap|dongthap)' THEN 'Đồng Tháp'
        WHEN {{ clean_col }} ~ '(hau giang|haugiang)' THEN 'Hậu Giang'
        WHEN {{ clean_col }} ~ '(kien giang|kiengiang)' THEN 'Kiên Giang'
        WHEN {{ clean_col }} ~ '(long an|longan)' THEN 'Long An'
        WHEN {{ clean_col }} ~ '(soc trang|socrang)' THEN 'Sóc Trăng'
        WHEN {{ clean_col }} ~ '(tien giang|tiengiang)' THEN 'Tiền Giang'
        WHEN {{ clean_col }} ~ '(tra vinh|travinh)' THEN 'Trà Vinh'
        WHEN {{ clean_col }} ~ '(vinh long|vinhlong)' THEN 'Vĩnh Long'

        ELSE 'Không xác định'
    END AS location
{% endmacro %}
