version: 2

models:
  - name: stg_jobs
    description: "Staging layer for jobs with normalized data"
    data_tests:
      - unique_combination:
          combination_of_columns: ['job_url', 'scraped_date']
      - row_count_in_range:
          min_rows: 10
          max_rows: 100000
    
    columns:
      - name: job_url
        description: "Unique URL of the job posting"
        data_tests:
          - not_null
          - valid_url
      
      - name: job_title
        description: "Normalized job title"
        data_tests:
          - not_null
      
      - name: company_name
        description: "Normalized company name (lowercase, trimmed)"
        data_tests:
          - not_null
      
      - name: salary
        description: "Salary information"
        data_tests:
          - salary_has_currency:
              severity: warn
      
      - name: location
        description: "Normalized job location"
        data_tests:
          - not_null:
              severity: warn
      
      - name: source_site
        description: "Source website name"
        data_tests:
          - not_null
          - valid_source_site
      
      - name: scraped_at
        description: "Timestamp when data was scraped"
        data_tests:
          - not_null
          - is_recent:
              days_ago: 7
      
      - name: scraped_date
        description: "Date when data was scraped (derived from scraped_at)"
        data_tests:
          - not_null
      
      - name: job_deadline
        description: "Job application deadline"
        data_tests:
          - deadline_after_scraped:
              deadline_column: job_deadline
              scraped_column: scraped_at
              severity: warn
