version: 2

models:
  # ============================================
  # Source-Specific Staging Models
  # ============================================
  
  - name: stg_joboko_jobs
    description: "Staging layer for JobOKO (vn.joboko.com) with source-specific cleaning logic"
    config:
      tags: ['staging', 'joboko']
    columns:
      - name: job_url
        description: "Unique URL of the job posting"
        tests:
          - not_null
          - unique
      
      - name: job_title
        description: "Normalized job title"
        tests:
          - not_null
      
      - name: company_name
        description: "Normalized company name (lowercase, trimmed)"
        tests:
          - not_null
      
      - name: salary
        description: "Salary normalized for JobOKO format (Negotiable, Competitive, or specific range)"
      
      - name: source_name
        description: "Source identifier"
        tests:
          - accepted_values:
              values: ['joboko']
      
      - name: scraped_at
        description: "Timestamp when data was scraped"
        tests:
          - not_null

  - name: stg_topcv_jobs
    description: "Staging layer for TopCV (topcv.vn) with source-specific cleaning logic"
    config:
      tags: ['staging', 'topcv']
    columns:
      - name: job_url
        description: "Unique URL of the job posting"
        tests:
          - not_null
          - unique
      
      - name: job_title
        description: "Normalized job title"
        tests:
          - not_null
      
      - name: company_name
        description: "Normalized company name (lowercase, trimmed)"
        tests:
          - not_null
      
      - name: education_level
        description: "Standardized education level (Bachelor, Master, PhD, etc.)"
        tests:
          - accepted_values:
              values: ['Bachelor', 'Associate', 'Vocational', 'Master', 'PhD', 'Not Required']
              severity: warn
      
      - name: source_name
        description: "Source identifier"
        tests:
          - accepted_values:
              values: ['topcv']
      
      - name: scraped_at
        description: "Timestamp when data was scraped"
        tests:
          - not_null

  - name: stg_vietnamworks_jobs
    description: "Staging layer for VietnamWorks (vietnamworks.com) with source-specific cleaning logic"
    config:
      tags: ['staging', 'vietnamworks']
    columns:
      - name: job_url
        description: "Unique URL of the job posting"
        tests:
          - not_null
          - unique
      
      - name: job_title
        description: "Normalized job title"
        tests:
          - not_null
      
      - name: company_name
        description: "Normalized company name (lowercase, trimmed)"
        tests:
          - not_null
      
      - name: experience_level
        description: "Standardized experience level"
        tests:
          - accepted_values:
              values: ['Entry Level', 'Junior', 'Experienced', 'Senior', 'Manager']
              severity: warn
      
      - name: source_name
        description: "Source identifier"
        tests:
          - accepted_values:
              values: ['vietnamworks']
      
      - name: scraped_at
        description: "Timestamp when data was scraped"
        tests:
          - not_null

  # ============================================
  # Unified Staging Model
  # ============================================
  
  - name: stg_jobs_unified
    description: "Unified staging layer combining all source-specific staging models"
    config:
      tags: ['staging', 'unified']
    data_tests:
      - unique:
          column_name: job_url
      - row_count_in_range:
          min_rows: 10
          max_rows: 100000
    
    columns:
      - name: job_url
        description: "Unique URL of the job posting"
        tests:
          - not_null
      
      - name: job_title
        description: "Normalized job title from all sources"
        tests:
          - not_null
      
      - name: company_name
        description: "Normalized company name (lowercase, trimmed) from all sources"
        tests:
          - not_null
      
      - name: salary
        description: "Salary information (normalized per source)"
      
      - name: location
        description: "Job location"
        tests:
          - not_null:
              severity: warn
      
      - name: source_site
        description: "Original source website domain"
        tests:
          - not_null
          - valid_source_site
      
      - name: source_name
        description: "Short source identifier (joboko, topcv, vietnamworks, etc.)"
        tests:
          - not_null
          - accepted_values:
              values: ['joboko', 'topcv', 'vietnamworks']
              # TODO: Thêm các source khác khi có
              severity: warn
      
      - name: scraped_at
        description: "Timestamp when data was scraped"
        tests:
          - not_null
          - is_recent:
              days_ago: 7
      
      - name: scraped_date
        description: "Date when data was scraped (derived from scraped_at)"
        tests:
          - not_null
      
      - name: job_deadline
        description: "Job application deadline (normalized format: DD/MM/YYYY)"
        tests:
          - deadline_after_scraped:
              deadline_column: job_deadline
              scraped_column: scraped_at
              severity: warn

  # ============================================
  # Legacy Model (giữ lại để tương thích)
  # ============================================
  
  - name: stg_jobs
    description: "[DEPRECATED] Original staging layer - use stg_jobs_unified instead"
    config:
      tags: ['staging', 'deprecated']
    meta:
      deprecated: true
      deprecation_reason: "Replaced by source-specific staging models and stg_jobs_unified"
